import { db } from './db.js';

const products = [
  { slug: 'seed-karistan',           image: '/images/products/seed-karistan.svg' },
  { slug: 'seed-topgan',             image: '/images/products/seed-topgan.svg' },
  { slug: 'seed-sorrento',           image: '/images/products/seed-sorrento.svg' },
  { slug: 'seed-farao',              image: '/images/products/seed-farao.svg' },
  { slug: 'seed-arashan',            image: '/images/products/seed-arashan.svg' },
  { slug: 'seed-crimson-ruby',       image: '/images/products/seed-crimson-ruby.svg' },
  { slug: 'seed-sarmat',             image: '/images/products/seed-sarmat.svg' },
  { slug: 'seed-el-wafi',            image: '/images/products/seed-el-wafi.svg' },
  { slug: 'seed-tomato-bull-heart',  image: '/images/products/seed-tomato-bull-heart.svg' },
  { slug: 'seed-tomato-krasnym',     image: '/images/products/seed-tomato-krasnym.svg' },
  { slug: 'seed-pepper-california',  image: '/images/products/seed-pepper-california.svg' },
  { slug: 'seed-cucumber-merenga',   image: '/images/products/seed-cucumber-merenga.svg' },
  { slug: 'seed-eggplant-valentina', image: '/images/products/seed-eggplant-valentina.svg' },
  { slug: 'seed-cabbage-megaton',    image: '/images/products/seed-cabbage-megaton.svg' },
  { slug: 'seed-carrot-nantes',      image: '/images/products/seed-carrot-nantes.svg' },
  { slug: 'seed-beet-bordeaux',      image: '/images/products/seed-beet-bordeaux.svg' },
  { slug: 'protection-targa-super',  image: '/images/products/protection-targa-super.svg' },
  { slug: 'protection-ridomil-gold', image: '/images/products/protection-ridomil-gold.svg' },
  { slug: 'protection-aktara',       image: '/images/products/protection-aktara.svg' },
  { slug: 'protection-roundup',      image: '/images/products/protection-roundup.svg' },
  { slug: 'protection-skor',         image: '/images/products/protection-skor.svg' },
  { slug: 'protection-thiram',       image: '/images/products/protection-thiram.svg' },
  { slug: 'fert-ammonium-nitrate',   image: '/images/products/fert-ammonium-nitrate.svg' },
  { slug: 'fert-superphosphate-double', image: '/images/products/fert-superphosphate-double.svg' },
  { slug: 'fert-potassium-sulfate',  image: '/images/products/fert-potassium-sulfate.svg' },
  { slug: 'fert-npk-161616',         image: '/images/products/fert-npk-161616.svg' },
  { slug: 'fert-urea',               image: '/images/products/fert-urea.svg' },
  { slug: 'fert-diamophoska',        image: '/images/products/fert-diamophoska.svg' },
  { slug: 'humate-potassium-liquid', image: '/images/products/humate-potassium-liquid.svg' },
  { slug: 'humate-potassium-powder', image: '/images/products/humate-potassium-powder.svg' },
  { slug: 'humate-plus-micro',       image: '/images/products/humate-plus-micro.svg' },
  { slug: 'humate-zamenit-tovar',    image: '/images/products/humate-zamenit-tovar.svg' },
  { slug: 'drip-tape-16mm',          image: '/images/products/drip-tape-16mm.svg' },
  { slug: 'drip-tape-16mm-30',       image: '/images/products/drip-tape-16mm-30.svg' },
  { slug: 'drip-tube-20mm',          image: '/images/products/drip-tube-20mm.svg' },
  { slug: 'drip-fitting-start-16',   image: '/images/products/drip-fitting-start-16.svg' },
  { slug: 'drip-valve-ball',         image: '/images/products/drip-valve-ball.svg' },
  { slug: 'drip-filter-120',         image: '/images/products/drip-filter-120.svg' },
  { slug: 'drip-connector-16',       image: '/images/products/drip-connector-16.svg' },
  { slug: 'motopump-mulat-sanreca',  image: '/images/products/motopump-mulat-sanreca.svg' },
  { slug: 'motopump-washer',         image: '/images/products/motopump-washer.svg' },
  { slug: 'motopump-technoline',     image: '/images/products/motopump-technoline.svg' },
  { slug: 'motopump-electrolight',   image: '/images/products/motopump-electrolight.svg' },
  { slug: 'fence-basic-kit',         image: '/images/products/fence-basic-kit.svg' },
  { slug: 'fence-sheep-goat',        image: '/images/products/fence-sheep-goat.svg' },
  { slug: 'fence-generator',         image: '/images/products/fence-generator.svg' },
  { slug: 'fence-wire-25',           image: '/images/products/fence-wire-25.svg' },
  { slug: 'fence-insulator-corner',  image: '/images/products/fence-insulator-corner.svg' },
  { slug: 'leaflet-a4-1000',         image: '/images/products/leaflet-a4-1000.svg' },
  { slug: 'leaflet-a5-1000',         image: '/images/products/leaflet-a5-1000.svg' },
  { slug: 'leaflet-euro-1000',       image: '/images/products/leaflet-euro-1000.svg' },
  { slug: 'cover-spanbond-17',       image: '/images/products/cover-spanbond-17.svg' },
  { slug: 'cover-spanbond-30',       image: '/images/products/cover-spanbond-30.svg' },
  { slug: 'cover-spanbond-60',       image: '/images/products/cover-spanbond-60.svg' },
  { slug: 'cover-lutrasil-23',       image: '/images/products/cover-lutrasil-23.svg' },
  { slug: 'mulch-film-black-100',    image: '/images/products/mulch-film-black-100.svg' },
  { slug: 'mulch-film-bw-120',       image: '/images/products/mulch-film-bw-120.svg' },
  { slug: 'mulch-film-brown-80',     image: '/images/products/mulch-film-brown-80.svg' },
  { slug: 'agrospan-100',            image: '/images/products/agrospan-100.svg' },
  { slug: 'agrospan-200',            image: '/images/products/agrospan-200.svg' },
  { slug: 'agrospan-black-150',      image: '/images/products/agrospan-black-150.svg' },
  { slug: 'arc-galv-2020',           image: '/images/products/arc-galv-2020.svg' },
  { slug: 'arc-galv-2525',           image: '/images/products/arc-galv-2525.svg' },
  { slug: 'arc-pvc-19',              image: '/images/products/arc-pvc-19.svg' },
  { slug: 'arc-crossbar-20',         image: '/images/products/arc-crossbar-20.svg' },
  { slug: 'gh-film-150-stab',        image: '/images/products/gh-film-150-stab.svg' },
  { slug: 'gh-film-200-arm',         image: '/images/products/gh-film-200-arm.svg' },
  { slug: 'gh-film-3l-150',          image: '/images/products/gh-film-3l-150.svg' },
  { slug: 'gh-film-ir',              image: '/images/products/gh-film-ir.svg' },
  { slug: 'peat-high-neutral',       image: '/images/products/peat-high-neutral.svg' },
  { slug: 'peat-low',                image: '/images/products/peat-low.svg' },
  { slug: 'peat-bag-50l',            image: '/images/products/peat-bag-50l.svg' },
  { slug: 'soil-universal-50l',      image: '/images/products/soil-universal-50l.svg' },
  { slug: 'soil-seedlings-10l',      image: '/images/products/soil-seedlings-10l.svg' },
  { slug: 'soil-tomato-pepper-10l',  image: '/images/products/soil-tomato-pepper-10l.svg' },
  { slug: 'soil-perlite-5l',         image: '/images/products/soil-perlite-5l.svg' },
  { slug: 'soil-vermiculite-5l',     image: '/images/products/soil-vermiculite-5l.svg' },
];

let updated = 0;
for (const p of products) {
  const result = await db.prepare('UPDATE products SET image = ? WHERE slug = ?').run(p.image, p.slug);
  if (result.changes > 0) updated++;
}

console.log(`✅ Updated ${updated}/${products.length} products with local images`);
